apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: haproxy-route
  namespace: haproxy
spec:
  host: haproxy.apps.homelab.yourdomain.com
  port:
    targetPort: 443
  to:
    kind: Service
    name: haproxy-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: passthrough