apiVersion: v1
kind: PersistentVolume
metadata:
  name: dummy-pv001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /nfs/path 
    server: 192.168.1.1 
  persistentVolumeReclaimPolicy: Delete 