
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
    layer: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: docker.io/haproxy:lts-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
            - containerPort: 8080
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/           
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
